--- #YAML:1.0
name:               XML-Compile-Cache
version:            0.991
abstract:           Cache compiled XML translators
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Report:          0.19
    Test::More:           0.54
    Test::Pod:            1.00
    XML::Compile:         1.2
    XML::Compile::Tester:  0.02
    XML::LibXML::Simple:  0.13
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
