--- #YAML:1.0
name:                XML-Compile-Cache
version:             0.95
abstract:            Cache compiled XML translators
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Log::Report:                   0.19
    Test::More:                    0.54
    Test::Pod:                     1.00
    XML::Compile:                  1.1
    XML::Compile::Tester:          0.02
    XML::LibXML::Simple:           0.13
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
